### ISSUE TITLE
Deleting a channel requires OpenAI credentials

### ISSUE THREAD

**Issue by danlamanna** [NotJoeMartinez/yt-fts#125]
This is due to the importing of `delete_channel_from_chroma` instantiating an `OpenAI` client.

See this traceback:
```
Traceback (most recent call last):
  File "/home/dan/p/yt-fts/.direnv/python-3.10.12/bin/yt-fts", line 33, in <module>
    sys.exit(load_entry_point('yt-fts', 'console_scripts', 'yt-fts')())
  File "/home/dan/p/yt-fts/.direnv/python-3.10.12/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/dan/p/yt-fts/.direnv/python-3.10.12/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/dan/p/yt-fts/.direnv/python-3.10.12/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dan/p/yt-fts/.direnv/python-3.10.12/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dan/p/yt-fts/.direnv/python-3.10.12/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/dan/p/yt-fts/yt_fts/yt_fts.py", line 144, in delete
    delete_channel(channel_id)
  File "/home/dan/p/yt-fts/yt_fts/db_utils.py", line 159, in delete_channel
    from .vector_search import delete_channel_from_chroma
  File "/home/dan/p/yt-fts/yt_fts/vector_search.py", line 7, in <module>
    from .embeddings import get_embedding
  File "/home/dan/p/yt-fts/yt_fts/embeddings.py", line 42, in <module>
    def get_embedding(text, model="text-embedding-ada-002", client=OpenAI()):
  File "/home/dan/p/yt-fts/.direnv/python-3.10.12/lib/python3.10/site-packages/openai/_client.py", line 92, in __init__
    raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable 
```

**Comment by NotJoeMartinez** [comment]
Interesting, was not aware that importing a function will cause the default args to be executed. Thanks for the fix.
