### ISSUE TITLE
Deleting a channel from the database results in an error relating to OpenAI

### ISSUE THREAD

**Issue by stevenjang1729** [NotJoeMartinez/yt-fts#128]
```
yt-fts delete --channel UC4tlrTXCBw6NPZ9nCA3_s9w 
```

```
Traceback (most recent call last):
  File "/opt/homebrew/bin/yt-fts", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/yt_fts/yt_fts.py", line 144, in delete
    delete_channel(channel_id)
  File "/opt/homebrew/lib/python3.11/site-packages/yt_fts/db_utils.py", line 159, in delete_channel
    from .vector_search import delete_channel_from_chroma 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/yt_fts/vector_search.py", line 7, in <module>
    from .embeddings import get_embedding
  File "/opt/homebrew/lib/python3.11/site-packages/yt_fts/embeddings.py", line 42, in <module>
    def get_embedding(text, model="text-embedding-ada-002", client=OpenAI()):
                                                                   ^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/openai/_client.py", line 92, in __init__
    raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
```

**Comment by NotJoeMartinez** [comment]
This was a bug effecting `0.1.40` and was fixed on `0.1.41`. see #121
