### ISSUE TITLE
Crash due to unicode decode error while getting video title from vtt

### ISSUE THREAD

**Issue by d89u** [NotJoeMartinez/yt-fts#138]
Might be a malformed character in a video title. Would it be possible to let yt-fts skip undefined characters and throw a warning instead of a crash?

Adding subtitles to database... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--
Traceback (most recent call last):
  File "c:\users\derja\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\derja\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\derja\AppData\Local\Programs\Python\Python39\Scripts\yt-fts.exe\__main__.py", line 7, in <module>
  File "c:\users\derja\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\derja\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "c:\users\derja\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\derja\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\derja\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\derja\appdata\local\programs\python\python39\lib\site-packages\yt_fts\yt_fts.py", line 63, in download
    foo = download_channel(channel_id, channel_name, language, number_of_jobs, s)
  File "c:\users\derja\appdata\local\programs\python\python39\lib\site-packages\yt_fts\download.py", line 264, in download_channel
    vtt_to_db(channel_id, tmp_dir, s)
  File "c:\users\derja\appdata\local\programs\python\python39\lib\site-packages\yt_fts\download.py", line 174, in vtt_to_db
    vid_title = get_vid_title(os.path.join(os.path.dirname(vtt), f'{vid_id}.info.json'))
  File "c:\users\derja\appdata\local\programs\python\python39\lib\site-packages\yt_fts\download.py", line 196, in get_vid_title
    return json.load(f)['title']
  File "c:\users\derja\appdata\local\programs\python\python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "c:\users\derja\appdata\local\programs\python\python39\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 273833: character maps to <undefined>

**Comment by AtaGunZ** [comment]
I have downloaded via pip and had the same issue. Made your suggested change: 
`def get_vid_title(info_json_path):
    """
    Retrieves video title from the info json file.
    """
    with open(info_json_path, 'r', encoding='utf-8', errors='ignore') as f:
        return json.load(f)['title']
`

and after that it worked.

**Comment by NotJoeMartinez** [comment]
Fixed in [v0.1.44](https://github.com/NotJoeMartinez/yt-fts/releases/tag/v0.1.44). Bug was introduced on [896f8fd](https://github.com/NotJoeMartinez/yt-fts/blame/58b538b7eeabcfc2ef400db9e154d1812f91a566/yt_fts/download.py#L176) by writing json to file system which will be encoded differently on Windows. Should be solved/prevented by specifying the `utf-8` encoding when using `json.load`, I don't have a Windows environment to test this in so feel free to make another issue if it persists.

**Comment by abdallahalsamman** [comment]
> what version are you on: yt-fts --version

`yt_fts version: 0.1.62`

Thank you for taking this into consideration
