### ISSUE TITLE
'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by sharpsteelsoftware** [NotJoeMartinez/yt-fts#150]
I get the following error when I try to yt-fts download URL

`Traceback (most recent call last):
  File "/Users/joseph/.pyenv/versions/3.12.3/bin/yt-fts", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/joseph/.pyenv/versions/3.12.3/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joseph/.pyenv/versions/3.12.3/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/joseph/.pyenv/versions/3.12.3/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joseph/.pyenv/versions/3.12.3/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joseph/.pyenv/versions/3.12.3/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joseph/.pyenv/versions/3.12.3/lib/python3.12/site-packages/yt_fts/yt_fts.py", line 52, in download
    channel_id = get_channel_id(url, s)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joseph/.pyenv/versions/3.12.3/lib/python3.12/site-packages/yt_fts/download.py", line 30, in get_channel_id
    channel_id = re.search('channelId":"(.{24})"', html).group(1)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'`

**Comment by NotJoeMartinez** [comment]
@sharpsteelsoftware thanks for reporting this, the issue was cause by YouTube changing the html of channel pages. 
Just fixed in [v0.1.51](https://github.com/NotJoeMartinez/yt-fts/releases/tag/v0.1.51) by searching for `<meta property="og:url" content="https://www.youtube.com/channel/UC3S8vxwRfqLBdIhgRlDRVzw"> ` in the HTML.
