### ISSUE TITLE
No such file or directory: 'yt-dlp'

### ISSUE THREAD

**Issue by saifrahmed** [NotJoeMartinez/yt-fts#5]
I tried to run the example python yt_fts.py download "https://www.youtube.com/@TimDillonShow/videos"
UC4woSp8ITBoYDmjkukhEhxg

and consistently end up with an error No such file or directory: 'yt-dlp'
```

Downloading channel
Saving vtt files to /var/folders/x7/0r36c9sn7yg7tvs5sdm471000000gn/T/tmpbrh06qzz
The Tim Dillon Show
Traceback (most recent call last):
  File "/Users/saif/WORKSPACE/yt-fts/yt_fts.py", line 273, in <module>
    cli()
  File "/Users/saif/opt/anaconda3/envs/yt/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/saif/opt/anaconda3/envs/yt/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/saif/opt/anaconda3/envs/yt/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/saif/opt/anaconda3/envs/yt/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/saif/opt/anaconda3/envs/yt/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/saif/WORKSPACE/yt-fts/yt_fts.py", line 31, in download
    download_channel(channel_id)
  File "/Users/saif/WORKSPACE/yt-fts/yt_fts.py", line 84, in download_channel
    subprocess.run([
  File "/Users/saif/opt/anaconda3/envs/yt/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/saif/opt/anaconda3/envs/yt/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/saif/opt/anaconda3/envs/yt/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'yt-dlp'
```

**Comment by TeddyBear06** [comment]
Looks like you're using an Anaconda virtual environnement (https://xkcd.com/1987/) and [yt-dlp](https://github.com/yt-dlp/yt-dlp/wiki/Installation) is not installed globally.

The best thing to do is to follow the [Installation](https://github.com/NotJoeMartinez/yt-fts#installation) instructions from the README.

**Comment by NotJoeMartinez** [comment]
This is probably related to yt-dlp not being installed globally on your machine or your virtual environment interfering with something. You can find more specific instructions on getting yt-dlp installed on their wiki: https://github.com/yt-dlp/yt-dlp/wiki/Installation
