### ISSUE TITLE
Support for Windows

### ISSUE THREAD

**Issue by vin-cf** [NotJoeMartinez/yt-fts#9]
Hi, this looks like a promising tool. A few points to hopefully help towards Windows support:

1. The README should be updated with instructions to set up a[ venv using activate.bat,](https://docs.python.org/3/library/venv.html).

2. What Python version(s) are supported? What versions do we know work with yt-fts?

3. Current state on Windows fails to run `download` command. Here is the output from my terminal:
```
python yt_fts.py download "https://www.youtube.com/@TimDillonShow/videos"

UC4woSp8ITBoYDmjkukhEhxg
Downloading channel
Saving vtt files to C:\Users\FOO\AppData\Local\Temp\tmp6oqtgfyb
The Tim Dillon Show
Traceback (most recent call last):
  File "C:\Users\FOO\Documents\git\yt-fts\yt_fts.py", line 273, in <module>
    cli()
  File "C:\Users\FOO\Documents\git\yt-fts\.env\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\Documents\git\yt-fts\.env\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\FOO\Documents\git\yt-fts\.env\Lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FOO\Documents\git\yt-fts\.env\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FOO\Documents\git\yt-fts\.env\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FOO\Documents\git\yt-fts\yt_fts.py", line 31, in download
    download_channel(channel_id)
  File "C:\Users\FOO\Documents\git\yt-fts\yt_fts.py", line 84, in download_channel
    subprocess.run([
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 1509, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by jsilence** [comment]
Was able to install and use on Windows 10 with stock Python 3.10 installed via Microsoft Store.
Also ran into the activate issue described. Could solve with a short Google magic. Still documentation for Windows would be welcomed. 
Download and seach does work.

**Comment by NotJoeMartinez** [comment]
Added winget to instructions and made link to yt-dlp install wiki more explicate on [320b225](https://github.com/NotJoeMartinez/yt-fts/commit/320b225fe3ae109646e4d5168bac608c042838e0)
